name: fineline_coffee
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  go_router: ^6.5.7
  http: ^0.13.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  shimmer: ^2.0.0
  loading_animation_widget: ^1.2.0+4
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.6
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  iconsax: ^0.0.8
  another_flushbar: ^1.12.30
  flutter_tabler_icons: ^1.11.0
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Neue Montreal
      fonts:
        - asset: assets/fonts/NeueMontrealBold.otf
          weight: 700
        - asset: assets/fonts/NeueMontrealMedium.otf
          weight: 500
        - asset: assets/fonts/NeueMontrealRegular.otf
          weight: 400
        - asset: assets/fonts/NeueMontrealLight.otf
          weight: 300
